### ISSUE TITLE
[REFACTOR] 4주차 코드 오타 리팩토링과 의존성 수정

### ISSUE THREAD

**Issue by Wonmoan** [kakao-tech-campus-2nd-step3/Team15_BE#35]
# 기타 이슈
- 4주차에 잘못 적힌 엔드포인트와 메서드명 수정하였습니다.
- `LocalDateTime` 직렬화 및 역직렬화가 안됩니다
  - 리팩토링후 코드 실행해보려고 하니 `LocalDateTime` 직렬화 및 역직렬화가 안됩니다
  - 설빈님 `WebConfig` 에서 `ObjectMapper` 빈 추가하고나서  날짜/시간 타입을 처리하는 기본 설정이 적용되지 않아 발생하는 것 같습니다.

## 📄 Description
- 기존 코드
```
 @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper();
    }
```    
- 수정 코드 
```
@Bean
    public ObjectMapper objectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JavaTimeModule());  // JavaTimeModule 등록
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);  // 날짜를 ISO 형식으로 직렬화
        return mapper;
    }
```
- build.gradle 에 의존성 추가
```
dependencies {
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'
}
```
이렇게 코드 수정하면 작동 됩니다. 
이렇게 수정해도 다른 곳에 영향을 받진 않을지 여쭤봅니다.
상관없으면 바로 pr날리겠습니다.

**Comment by Profile-exe** [comment]
카카오 소셜 로그인 구현부분을 보시면 `RestTemplate` 대신 `RestClient`를 사용합니다. 이를 사용하면 외부 API를 사용할 때 `DTO`만 잘 정의한다면 `ObjectMapper`를 사용하지 않고도 자동으로 파싱이 됩니다. 덕분에 코드도 훨 간결해집니다.

따라서 `WebConfig`에서 `ObjectMapper`와 `RestTemplate` 빈을 지우고 `RestClient`만 빈으로 등록하여 주입받고 사용하도록 변경하면 좋을 것 같은데, 어떻게 생각하시나요?

**Comment by Wonmoan** [comment]
좋은 방법인 것 같습니다
일단 제 오타 땜에 실행 안되는 상황이니 오타 수정한 것 다른 분들 작업하실때 반영 되게 pr날릴 예정이었습니다. 
설빈님 괜찮으시다면 일단 아래같이 해놓고
```
@Configuration
public class WebConfig {

    @Bean
    public RestClient restClient() {
        return RestClient.builder().build();
    }
}
```
pr날려도 될까요

**Comment by seolbin96** [comment]
넵 좋습니다!!
